[package]
name = "rustyforge"
version = "0.4.1"
authors = ["konni332"]
edition = "2024"
description = "A fast build tool for C, written in Rust"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/konni332/rustyforge"
keywords = ["cli", "build", "C", "tool"]
categories = ["command-line-utilities", "development-tools::build-utils"]

[[bin]]
name = "rustyforge"
path = "src/main.rs"

[lib]
name = "rustyforge_core"
path = "src/lib.rs"

[features]
default = ["term-colors"]
term-colors = []

[dependencies]
serde = { version = "1.0", features = ["derive"]}
toml = "0.9"
clap = { version = "4.5", features = ["derive"]}
rayon = "1.11"
globset = "0.4"
jwalk = "0.8"
tempfile = "3.24"
which = "8"
dirs-next = "2"
twox-hash = "2.1"
postcard = { version = "1.1", features = ["alloc"] }
indicatif = "0.18"
color-eyre = "0.6"
thiserror = "2.0"
miette = "7.6"
